apiVersion: v1
kind: Service
metadata:
  name: nodejs-shark-app-lb
spec:
  selector:
    app: nodejs-shark-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
