apiVersion: v1
kind: Service
metadata:
  name: nodejs-shark-app-8080-lb
spec:
  selector:
    app: nodejs-shark-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
